### ISSUE TITLE
Creating Selectable USA Regions

### ISSUE THREAD

**Issue by zkm** [10bestdesign/jqvmap#241]
I have created a map with predefined USA Region select options. However if you were to select one of the regions (i.e. Midwest), select a state (i.e. Illinois), select a different region (i.e. South), and finally select  the original region (i.e. Midwest) it will all go away. 
- [Demo](http://s.codepen.io/zkm/debug/ezNGMG)
- [CodePen](http://codepen.io/zkm/pen/ezNGMG/)

**Comment by ZKM** [comment]
UPDATE: When you attempt to deselect state/region that is not selected it will blow up and deselect everything.

**Comment by manifestinteractive** [comment]
@ZKM This is certainly an interesting bug and I appreciate you making those demos.  I will be tinkering with this myself over the next few days to see if I can get to the root cause.

**Comment by ZKM** [comment]
@manifestinteractive I did find a fix and updated the codepen. I added a conditional around the select/deselect function.
