### ISSUE TITLE
Move map functionality

### ISSUE THREAD

**Issue by ekaratzaferis** [10bestdesign/jqvmap#296]
Is there any way to change the map's position other than using the drag n' drop feature?

At the moment I'm applying my own translate matrix to change the map's position, but this is not entirely compatible with the drag n' drop feature. 

I believe the last position of the map, lets say [0,0], is cached inside the module and every drag event starts from there. If my own matrix moves the map to [8,8], then the next time I'm dragging it, it will be drawn at [0,0] and carry on from there, which is not pretty :)

**Comment by phoopee3** [comment]
I ended up writing a custom function that I passed x, y, zoom, and zoomcurstep too, and then overwrote this.transX, this.transY, this.scale, and this.zoomCurStep. Then called this.setScale and this.applyTransform as necessary.
